// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARSx4VaDdXwFVZ3PEGKTUnt7MdfEfPc9A',
    appId: '1:76869443049:web:1d4504c8f1b24571d4ff78',
    messagingSenderId: '76869443049',
    projectId: 'juniorhub-bd73d',
    authDomain: 'juniorhub-bd73d.firebaseapp.com',
    storageBucket: 'juniorhub-bd73d.firebasestorage.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfx4E_OjG_I1tfngTM08wySKxGr7GTfdk',
    appId: '1:76869443049:ios:3cb8e773977ef789d4ff78',
    messagingSenderId: '76869443049',
    projectId: 'juniorhub-bd73d',
    storageBucket: 'juniorhub-bd73d.firebasestorage.app',
    iosBundleId: 'n',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARSx4VaDdXwFVZ3PEGKTUnt7MdfEfPc9A',
    appId: '1:76869443049:web:1d4504c8f1b24571d4ff78',
    messagingSenderId: '76869443049',
    projectId: 'juniorhub-bd73d',
    authDomain: 'juniorhub-bd73d.firebaseapp.com',
    storageBucket: 'juniorhub-bd73d.firebasestorage.app',
  );
}
